#!/bin/sh 
#

set -x

#
# React
#

npm i prop-types@15.7.2 --save


#
#
#

npm i classnames --save

npm i @babel/runtime --save

npm i eslint --save-dev

npm i @babel/core babel-eslint babel-jest babel-loader --save-dev

npm i @babel/plugin-proposal-class-properties @babel/plugin-proposal-object-rest-spread @babel/plugin-syntax-dynamic-import \
@babel/plugin-transform-runtime @babel/preset-env @babel/preset-react @babel/preset-typescript --save-dev

npm i eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks --save-dev

npm i eslint-config-airbnb eslint-config-prettier eslint-webpack-plugin --save-dev

set +x

		"@babel/core": "^7.12.10",
		"@babel/plugin-proposal-class-properties": "^7.12.1",
		"@babel/plugin-proposal-object-rest-spread": "^7.12.1",
		"@babel/plugin-syntax-dynamic-import": "^7.8.3",
		"@babel/plugin-transform-runtime": "^7.12.10",
		"@babel/preset-env": "^7.12.10",
		"@babel/preset-react": "^7.12.10",
		"@babel/preset-typescript": "^7.12.7",
		"babel-eslint": "^10.1.0",
		"babel-jest": "^26.6.3",
		"babel-loader": "^8.2.2",
		"eslint": "^7.15.0",
		"eslint-config-airbnb": "^18.2.1",
		"eslint-config-prettier": "^7.0.0",
		"eslint-plugin-import": "^2.22.1",
		"eslint-plugin-jsx-a11y": "^6.4.1",
		"eslint-plugin-react": "^7.21.5",
		"eslint-plugin-react-hooks": "^4.2.0",
		"eslint-webpack-plugin": "^2.4.1",
