#!/bin/sh
#
#  script to create inventory
#
echo "create inventory"
#
INPUT_FILE="products_export_1.csv"
OUTPUT_FILE="inventory_export_1.csv"

echo "Handle,Title,Body (HTML),Vendor,Type,Tags,Published,Option1 Name,Option1 Value,Option2 Name,Option2 Value,Option3 Name,Option3 Value,Variant SKU,Warehouse" > $OUTPUT_FILE
#
cat $INPUT_FILE | awk -F, '{print $1"," $2"," $8"," $9"," $10"," $11"," $12"," $13"," $14",25"'} | awk 'NR!=1 {print} '>> $OUTPUT_FILE


cat $OUTPUT_FILE
